SET TERMOUT OFF FEEDBACK OFF TIMING OFF

SET ARRAYSIZE       100
SET AUTOCOMMIT      OFF
SET AUTOPRINT       OFF
SET AUTORECOVERY    OFF
SET AUTOTRACE       OFF
SET BLOCKTERMINATOR "."
SET CMDSEP          OFF
SET COLSEP          " "
SET CONCAT          "."
SET COPYCOMMIT      0
SET COPYTYPECHECK   ON
SET DEFINE          "&"
SET DESCRIBE        DEPTH 1 LINENUM OFF INDENT ON
SET ECHO            OFF
SET EMBEDDED        ON
SET ERRORLOGGING    OFF
SET ESCAPE          OFF
SET ESCCHAR         OFF
SET EXITCOMMIT      ON
SET FEEDBACK        OFF
SET FLAGGER         OFF
SET FLUSH           ON
SET HEADING         ON
SET HEADSEP         "|"
SET LINESIZE        200
SET LOBOFFSET       1
SET LOGSOURCE       ""
SET LONG            80
SET LONGCHUNKSIZE   80
SET NEWPAGE         1
SET NULL            ""
SET NUMFORMAT       ""
SET NUMWIDTH        16
SET PAGESIZE        0
SET PAUSE           OFF
SET RECSEP          WRAP
SET RECSEPCHAR      " "
SET SECUREDCOL      OFF
SET SERVEROUTPUT    ON SIZE UNLIMITED FORMAT TRUNCATED
SET SHIFTINOUT      INVISIBLE
SET SHOWMODE        OFF
SET SQLBLANKLINES   OFF
SET SQLCASE         MIXED
SET SQLCONTINUE     "  >  "
SET SQLNUMBER       ON
SET SQLPREFIX       "#"
SET SQLTERMINATOR   ";"
SET SUFFIX          "sql"
SET TAB             OFF
SET TERMOUT         ON
SET TIMING          OFF
SET TRIMOUT         ON
SET TRIMSPOOL       OFF
SET UNDERLINE       "-"
SET VERIFY          OFF
SET WRAP            OFF
SET TERMOUT ON FEEDBACK ON TIMING ON

PROMPT Default settings applied.
